// app/components/AddMeta.tsx
"use client";
import React, { useState } from "react";
import { supabase } from "@/lib/supabase";
import { fetchTags } from "@/lib/data";
import Image from "next/image";
import { v4 as uuidv4 } from 'uuid';
import AsyncCreatableSelect from 'react-select/async-creatable';
import type { MultiValue, ActionMeta } from "react-select";

export interface MetaTag {
  id: string;
  user_id?: string;
  country_code?: string;
  tags: string[];
  name: string;
  description: string;
  image_url?: string;
  metadata?: Record<string, any>;
  add_date?: string;
  edit_date?: string;
  created_by?: string;
  updated_by?: string;
  original_id?: string;
}

type AddMetaProps = {
  country: {
    code: string;
    name: string;
  };
  onMetaAddedCallBack: () => void;
};

const AddMeta = ({ country, onMetaAddedCallBack }: AddMetaProps) => {
  const [creatingMeta, setCreatingMeta] = useState(false);
  const [selectedTags, setSelectedTags] = useState<string[]>([]);

  const [formData, setFormData] = useState<{
    name: string;
    description: string;
    tags: string[];
    file: File | null;
  }>({
    name: "",
    description: "",
    tags: [],
    file: null,
  });
  const [preview, setPreview] = useState<string | null>(null);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const imageFile = e.target.files?.[0];
    const newImage = imageFile ? renameImage(imageFile) : null;
    setFormData((prevData) => ({
      ...prevData,
      file: newImage,
    }));

    if (newImage) {
      setPreview(URL.createObjectURL(newImage));
    } else {
      setPreview(null);
    }
  };

  const onPasteFile = (e: React.ClipboardEvent<HTMLInputElement>) => {
    const items = e.clipboardData.items;
    const imageFile = items[0].getAsFile();
    const newImage = imageFile ? renameImage(imageFile) : null;
    if (newImage && imageFile?.type.startsWith('image/')) {
      const t = URL.createObjectURL(newImage);
      setPreview(t);
      setFormData((d) => ({
        ...d,
        file: newImage,
      }));
    } else {
      alert("Please paste a valid image URL (jpg, png, jpeg).");
    }
  };

  const renameImage = (imageFile: File) => {
    const uniqueId = uuidv4();
    const uniqueFileName = `${uniqueId}_${imageFile.name}`;
    const renamedFile = new File([imageFile], uniqueFileName, {
      type: imageFile.type,
    });
    return renamedFile;
  };

  const onMetaAdded = () => {
    onMetaAddedCallBack();
    setFormData({
      name: "",
      description: "",
      tags: [],
      file: null,
    });
    setPreview(null);
    setSelectedTags([]);
  };

  const addMetaClick = async () => {
    setCreatingMeta(!creatingMeta);
    if (creatingMeta && formData.file !== null) {
      const res = await createMeta(formData);
      if (!res.error) {
        onMetaAdded();
      }
      setCreatingMeta(false);
    }
  };

  const uploadImage = async (file: File) => {
    const sanitizedFileName = file.name.replace(/[^a-zA-Z0-9.]/g, '_');
    const { data, error } = await supabase.storage
      .from("images")
      .upload(`public/${sanitizedFileName}`, file);
    if (error) {
      console.error("Erreur lors du téléchargement de l'image :", error);
      return null;
    }
    return data.path;
  };

  const getPublicUrl = (imagePath: string | null) => {
    if (!imagePath) return null;
    const res = supabase.storage
      .from('images')
      .getPublicUrl(imagePath);
    return res.data.publicUrl;
  };

  const createMeta = async (data: {
    name: string;
    description: string;
    tags: string[];
    file: File | null;
  }) => {
    const imagePath = data.file ? await uploadImage(data.file) : null;
    const imageUrl = getPublicUrl(imagePath);
    return await insertMeta(data, imageUrl, selectedTags);
  };

  const insertMeta = async (metaData: {
    name: string;
    description: string;
    tags: string[];
  }, imagePath: string | null, selectedTags: string[]) => {
    return await supabase
      .from("metas")
      .insert([
        {
          name: metaData.name,
          description: metaData.description,
          tags: selectedTags,
          user_id: "fb7a25b6-d374-4d91-a658-2d8f4f9c90f1",
          country_code: country.code,
          image_url: imagePath,
        },
      ])
      .select();
  };

  const createTag = async (name: string) => {
    console.log("Création du tag :", name);
    const { error } = await supabase
      .from("meta_tags")
      .insert({ name, country_code: country.code, created_at: new Date() });

    if (error) {
      console.error("Erreur lors de la création du tag :", error);
      return false;
    }

    setSelectedTags((prev) => [...prev, name]);
    return true;
  };

  const onTagInputChange = (
    newValue: MultiValue<{ label: string; value: string }>,
    actionMeta: ActionMeta<{ label: string; value: string }>
  ) => {
    const tags = newValue.map((tag) => tag.value);
    setSelectedTags(tags);
  };

  const loadTags = async (inputValue: string) => {
    console.log("Chargement des tags avec inputValue :", inputValue);
    const tags = await fetchTags();
    console.log("Chargement des tags :", tags);
    return (
      tags?.filter(tag =>
        tag.name.toLowerCase().includes(inputValue.toLowerCase())
      ).map((tag) => ({
        label: tag.name,
        value: tag.name,
      })) || []
    );
  };

  return (
    <div className="add-meta-container">
      {creatingMeta && (
        <div className="add-meta-form flex mb-4">
          <div className="image-container p-4 m-5">
            {!preview ? (
              <div className="h-full">
                <div
                  className="file-input-container flex items-center justify-center h-1/2"
                  onClick={() => document.getElementById("file-upload-input")?.click()}
                  style={{ cursor: "pointer" }}
                >
                  <input
                    id="file-upload-input"
                    type="file"
                    name="file"
                    onChange={handleFileChange}
                    style={{ display: "none" }}
                  />
                  <div>Upload your picture</div>
                  <svg width="23" height="23" viewBox="0 0 23 23" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.5238 20.8095H2.19048V5.47619H12.0476V3.28571H2.19048C0.985714 3.28571 0 4.27143 0 5.47619V20.8095C0 22.0143 0.985714 23 2.19048 23H17.5238C18.7286 23 19.7143 22.0143 19.7143 20.8095V10.9524H17.5238V20.8095ZM8.99191 17.3376L6.84524 14.7529L3.83333 18.619H15.881L12.0038 13.4605L8.99191 17.3376ZM19.7143 3.28571V0H17.5238V3.28571H14.2381C14.249 3.29667 14.2381 5.47619 14.2381 5.47619H17.5238V8.75095C17.5348 8.7619 19.7143 8.75095 19.7143 8.75095V5.47619H23V3.28571H19.7143Z" fill="black" />
                  </svg>
                </div>
                <div
                  className="file-input-container flex items-center justify-center h-1/2"
                  style={{ height: "50%" }}
                >
                  <input
                    type="text"
                    placeholder="Or paste your image here"
                    onPaste={onPasteFile}
                    className="paste-image-input border-none"
                  />
                </div>
              </div>
            ) : (
              <Image src={preview} alt="metaImage" height={200} width={250} className="max-h-full object-cover" />
            )}
          </div>
          <div className="meta-inputs m-5 flex flex-col w-full">
            <div className="flex w-full space-x-2">
              <input
                type="text"
                value={formData.name}
                onChange={handleChange}
                placeholder="Name"
                name="name"
                className="meta-name-input border-none w-1/2 px-3 py-2"
              />
              {/* <div className="tags-container flex flex-wrap w-1/2">
                {selectedTags.map((tag, index) => (
                  <span key={index} className="tag-item bg-gray-200 rounded-full px-2 py-1 mr-2 mb-2">
                    {tag.trim()}
                  </span>
                ))}
              </div> */}
              <AsyncCreatableSelect
                classNamePrefix="custom-select"
                isMulti
                isClearable
                placeholder="Tags..."
                value={selectedTags.map((tag) => ({ label: tag, value: tag }))}
                onChange={onTagInputChange}
                onCreateOption={(inputValue) => {
                  const trimmed = inputValue.trim();
                  if (trimmed && !selectedTags.includes(trimmed)) {
                    createTag(trimmed);
                  }
                }}
                loadOptions={loadTags}
                defaultOptions
                cacheOptions
                className="w-full"
                aria-label="tag-selection"
              />
            </div>
            <textarea
              rows={4}
              value={formData.description}
              onChange={handleChange}
              placeholder="Description"
              name="description"
              className="meta-description-input border-none w-full resize-none"
            />
          </div>
        </div>
      )}
      <button
        className="add-meta-button group disabled cursor-pointer bg-transparent text-black hover:bg-black hover:text-white transition-all duration-300"
        onClick={addMetaClick}
        disabled={creatingMeta && (!formData.name || !formData.description || !formData.file)}
      >
        {creatingMeta ? "Add the meta" : "Add a meta"}
        {creatingMeta ? (
          // Icône check dans un cercle
          <svg
            width="21"
            height="20"
            viewBox="0 0 21 20"
            xmlns="http://www.w3.org/2000/svg"
            className="ml-2 text-black group-hover:text-white transition-all duration-300"
          >
            <circle
              cx="10.5"
              cy="10"
              r="9"
              stroke="currentColor"
              strokeWidth="2"
              fill="none"
            />
            <path
              d="M6.5 10.5L9.5 13.5L15 8"
              stroke="currentColor"
              strokeWidth="2"
              fill="none"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        ) : (
          // Icône +
          <svg
            width="21"
            height="20"
            viewBox="0 0 21 20"
            xmlns="http://www.w3.org/2000/svg"
            className="ml-2 text-black group-hover:text-white transition-all duration-300"
          >
            <path
              d="M10.5 0C4.989 0 0.5 4.489 0.5 10C0.5 15.511 4.989 20 10.5 20C16.011 20 20.5 15.511 20.5 10C20.5 4.489 16.011 0 10.5 0ZM10.5 2C14.9301 2 18.5 5.56988 18.5 10C18.5 14.4301 14.9301 18 10.5 18C6.06988 18 2.5 14.4301 2.5 10C2.5 5.56988 6.06988 2 10.5 2ZM9.5 5V9H5.5V11H9.5V15H11.5V11H15.5V9H11.5V5H9.5Z"
              fill="currentColor"
            />
          </svg>
        )}
      </button>
    </div>
  );
};

export default AddMeta;

// app/components/meta/AddMeta.vue
<template>
  <div class="add-meta-container space-y-4">
    <transition name="fade">
      <div class="add-meta-block border-2 border-black">
        <form id="add-meta-form" @submit.prevent="onSubmit">
          <div v-if="isCreating" class="flex flex-col gap-6  bg-white/95 p-6 lg:flex-row">
            <div class="media-panel flex flex-1 cursor-pointer flex-col " @dragover.prevent @drop.prevent="onDrop">
              <input ref="fileInput" type="file" accept="image/*" class="hidden" @change="onFileChange" />
              <div class="image-container border-2 border-black">
                <div v-if="!preview"
                  class="flex  h-48 flex-col items-center justify-center gap-3 text-sm text-neutral-600"
                  @click="triggerFileDialog">

                  <!-- use the SVG file from public/ so it's the actual addImage.svg asset -->
                  <img src="/addImage.svg" alt="Add image" class="w-6 h-6 text-neutral-500 mx-auto" />

                  <p class="text-xs text-neutral-400">Click or drag an image</p>
                </div>
                <div v-else class="relative h-48 overflow-hidden">
                  <img :src="preview" alt="Prévisualisation" class="h-full w-full object-cover" />
                  <button type="button"
                    class="absolute right-3 top-3  bg-white/80 px-3 py-1 text-xs border-1 border-black cursor-pointer"
                    @click.stop="resetImage">
                    clear
                  </button>
                </div>
              </div>
              <input ref="pasteInput" type="text" class="border-2 border-black px-4 py-2 mt-2 text-sm"
                placeholder="Or paste your image" @paste.prevent="onPaste" @click.prevent="" />
            </div>

            <div class="flex flex-1 flex-col gap-4">
              <div class="flex flex-col gap-4 lg:flex-row">
                <input v-model="form.name" type="text" class="w-full px-5 py-2 text-base h-10 shadow-inner"
                  placeholder="Meta name" />
                <div class="tag-select w-full px-4">
                  <div class="relative">
                    <input v-model="tagSearch" type="text" class="w-full px-4 py-2 text-sm" placeholder="Tags..."
                      @keydown.enter.prevent="handleTagEnter" @input="filterSuggestions" @focus="tagFocused = true"
                      @blur="tagFocused = false" />
                    <ul v-if="suggestions.length && tagFocused"
                      class="suggestions absolute z-10 mt-2 max-h-40 w-full overflow-y-auto border-2 border-black bg-white text-sm">
                      <li v-for="suggestion in suggestions" :key="suggestion"
                        class="cursor-pointer px-4 py-2 hover:bg-neutral-100" @pointerdown.prevent="addTag(suggestion)">
                        {{ truncate(suggestion) }}
                      </li>
                    </ul>
                  </div>
                </div>

              </div>
              <div class="">
                <span v-for="tag in selectedTags" :key="tag"
                  class="inline-flex items-center gap-1 bg-black px-3 py-1 text-xs font-medium uppercase tracking-[0.3em] text-white overflow-hidden mr-2">
                  <span class="block truncate max-w-[140px]" :title="tag">{{ truncate(tag) }}</span>
                  <button type="button" class="text-white/70" @click="removeTag(tag)">&times;</button>
                </span>
              </div>

              <textarea v-model="form.description" rows="3" class="w-full shadow-inner px-5 py-4 text-base"
                placeholder="Description"></textarea>
            </div>
            <img class="close-add-meta cursor-pointer" :src="closeIcon" @click="onClose">
          </div>
          <button type="button"
            class="add-meta-button group flex items-center justify-center transition hover:bg-black hover:text-white cursor-pointer"
            :class="isCreating ? 'border-1 border-black' : ''"
            :disabled="isCreating && (!isValid || !country || submitting)"
            :style="{ width: isCreating ? 'calc(100% - 48px)' : '100%', margin: isCreating ? '24px' : '0' }"
            @click="onSubmit">

            {{ submitting ? 'Saving…' : isCreating ? 'Add the meta' : 'Add a meta' }}
            <span class="ml-3 flex items-center justify-center">
              <!-- spinner -->
              <svg v-if="submitting" width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"
                class="animate-spin">
                <circle cx="10" cy="10" r="8" stroke="currentColor" stroke-width="2" fill="none" stroke-opacity="0.25" />
                <path d="M10 2a8 8 0 0 1 8 8" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" />
              </svg>
              <!-- plus -->
              <svg v-else-if="!isCreating" width="21" height="20" viewBox="0 0 21 20" xmlns="http://www.w3.org/2000/svg"
                class="transition group-hover:text-white">
                <path
                  d="M10.5 0C4.989 0 0.5 4.489 0.5 10C0.5 15.511 4.989 20 10.5 20C16.011 20 20.5 15.511 20.5 10C20.5 4.489 16.011 0 10.5 0ZM10.5 2C14.9301 2 18.5 5.56988 18.5 10C18.5 14.4301 14.9301 18 10.5 18C6.06988 18 2.5 14.4301 2.5 10C2.5 5.56988 6.06988 2 10.5 2ZM9.5 5V9H5.5V11H9.5V15H11.5V11H15.5V9H11.5V5H9.5Z"
                  fill="currentColor" />
              </svg>
              <!-- check -->
              <svg v-else width="21" height="20" viewBox="0 0 21 20" xmlns="http://www.w3.org/2000/svg"
                class="transition group-hover:text-white">
                <circle cx="10.5" cy="10" r="9" stroke="currentColor" stroke-width="2" fill="none" />
                <path d="M6.5 10.5L9.5 13.5L15 8" stroke="currentColor" stroke-width="2" fill="none"
                  stroke-linecap="round" stroke-linejoin="round" />
              </svg>
            </span>
          </button>
        </form>
      </div>
    </transition>


    <p v-if="submitError" class="text-sm text-rose-600">{{ submitError }}</p>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useSupabaseClient } from '~/lib/supabase.client'
import { useAuthStore } from '~/stores/auth'
import { createMeta as apiCreateMeta } from '~/lib/supabase.api'
import closeIcon from '@/assets/icons/close.svg'
const onClose = () => {
  isCreating.value = false
}

import type { Meta } from '@/types/meta'

const props = defineProps<{ country: { code: string; name: string } | null }>()
const emit = defineEmits<{ (e: 'meta-added', meta: Meta): void }>()

const supabase = useSupabaseClient()
const authStore = useAuthStore()

const isCreating = ref(!props.country)
const submitting = ref(false)
const submitError = ref<string | null>(null)
const preview = ref<string | null>(null)
const fileInput = ref<HTMLInputElement | null>(null)
const pasteInput = ref<HTMLInputElement | null>(null)
const availableTagNames = ref<string[]>([])
const selectedTags = ref<string[]>([])
const tagSearch = ref('')
const suggestions = ref<string[]>([])
const tagFocused = ref(false)

const form = reactive({
  name: '',
  description: '',
  file: null as File | null,
})


const countryCode = computed(() => props.country?.code?.toUpperCase?.())

const isValid = computed(() => !!form.name && !!form.description && !!form.file && !!countryCode.value)

// Move loadTags definition above watcher to fix ReferenceError
const loadTags = async () => {
  const { data, error } = await supabase
    .from('meta_tags')
    .select('name')
    .order('name')
  if (error) {
    console.error('Error fetching tags', error)
    availableTagNames.value = []
    return
  }
  // deduplicate tag names across countries
  availableTagNames.value = [...new Set((data ?? []).map((t) => t.name))]
  filterSuggestions()
}

watch(countryCode, async (val) => {
  selectedTags.value = []
  if (!val) {
    availableTagNames.value = []
    isCreating.value = true
    return
  }
  await loadTags()
}, { immediate: true })

watch(() => props.country, (val) => {
  if (!val) {
    isCreating.value = true
  }
})

const filterSuggestions = () => {
  const query = tagSearch.value.trim().toLowerCase()
  const base = availableTagNames.value.filter((tag) => !selectedTags.value.includes(tag))
  suggestions.value = query ? base.filter((tag) => tag.toLowerCase().includes(query)) : base.slice(0, 8)
}

const addTag = (tag: string) => {
  const value = normalizeTag(tag)
  if (!value || selectedTags.value.includes(value)) return
  selectedTags.value = [...selectedTags.value, value]
  tagSearch.value = ''
  suggestions.value = []
}

const truncate = (s: string, max = 20) => {
  if (!s) return s
  return s.length > max ? s.slice(0, max) + '…' : s
}

const removeTag = (tag: string) => {
  selectedTags.value = selectedTags.value.filter((t) => t !== tag)
}

const normalizeTag = (s: string) => s.trim().charAt(0).toUpperCase() + s.trim().slice(1).toLowerCase()

const handleTagEnter = async () => {
  const value = normalizeTag(tagSearch.value)
  if (!value) return
  if (availableTagNames.value.includes(value)) {
    addTag(value)
  } else {
    await createTag(value)
  }
}

const createTag = async (value: string) => {
  if (!countryCode.value) return
  try {
    await supabase
      .from('meta_tags')
      .upsert({ name: value }, { onConflict: 'name' })
    if (!availableTagNames.value.includes(value)) {
      availableTagNames.value.push(value)
    }
    addTag(value)
  } catch (err) {
    console.error('Error creating tag', err)
    // Tag creation failed but still add it locally to selectedTags
    addTag(value)
  }
}

const triggerFileDialog = () => {
  fileInput.value?.click()
}

const onFileChange = (event: Event) => {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  setFile(file || null)
}

const onDrop = (event: DragEvent) => {
  const file = event.dataTransfer?.files?.[0]
  setFile(file || null)
}

const onPaste = (event: ClipboardEvent) => {
  const file = event.clipboardData?.files?.[0]
  if (file && file.type.startsWith('image/')) {
    setFile(file)
  } else {
    const text = event.clipboardData?.getData('text')
    if (text) {
      submitError.value = 'L\'image collée doit être un fichier.'
      window.setTimeout(() => (submitError.value = null), 3000)
    }
  }
}

const revokePreview = () => {
  if (preview.value) {
    URL.revokeObjectURL(preview.value)
    preview.value = null
  }
}

const setFile = (file: File | null) => {
  revokePreview()
  if (!file) {
    form.file = null
    return
  }
  form.file = renameFile(file)
  preview.value = URL.createObjectURL(form.file)
}

const resetImage = () => {
  form.file = null
  revokePreview()
}

const generateId = () => {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID()
  }
  return Math.random().toString(36).slice(2)
}

const renameFile = (file: File) => {
  const extension = file.name.split('.').pop()
  const newName = `${generateId()}.${extension}`
  return new File([file], newName, { type: file.type })
}


const uploadImage = async (file: File) => {
  if (!authStore.user) throw new Error('Non authentifié')

  const path = `public/${file.name}`

  const { error } = await supabase.storage
    .from('images')
    .upload(path, file)

  if (error) throw error

  const { data } = supabase.storage.from('images').getPublicUrl(path)
  return data.publicUrl
}

const onSubmit = async () => {
  if (!isCreating.value) {
    if (!ensureAccess()) return
    isCreating.value = true
    return
  }
  if (!isValid.value || !props.country) return
  await submit()
}

const ensureAccess = () => {
  if (!props.country) {
    submitError.value = 'Sélectionne un pays pour ajouter une méta.'
    return false
  }
  if (!authStore.isLogged) {
    authStore.isLoginOpen = true
    return false
  }
  return true
}

const submit = async () => {
  if (!isValid.value || !countryCode.value || !form.file) return
  submitting.value = true
  submitError.value = null
  try {
    const imageUrl = await uploadImage(form.file)
    const payload = {
      name: form.name,
      description: form.description,
      tags: selectedTags.value,
      image_url: imageUrl,
      country_code: countryCode.value,
      user_id: authStore.user?.id
    }
    const { data, error } = await apiCreateMeta(payload)
    if (error) throw error
    emit('meta-added', data as Meta)
    resetForm()
    isCreating.value = false
  } catch (err: any) {
    console.error(err)
    submitError.value = err?.message ?? 'Impossible de créer la méta'
  } finally {
    submitting.value = false
  }
}

const resetForm = () => {
  form.name = ''
  form.description = ''
  form.file = null
  revokePreview()
  selectedTags.value = []
  tagSearch.value = ''
  suggestions.value = []
  submitError.value = null
}
</script>

<style scoped>
.add-meta-button {
  /* Add a meta */
  box-sizing: border-box;
  /* Auto layout */
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  padding: 16px 0px;
  gap: 10px;

  width: 100%;
  height: 56px;

  /* Inside auto layout */
  flex: none;
  order: 0;
  align-self: stretch;
  flex-grow: 0;

}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease, transform 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(-12px);
}

.close-add-meta {
  position: relative;
  top: 0px;
  right: 0px;
  height: 24px;
  width: 24px;
}
</style>
