// app/components/CountryList.tsx
"use client";

import { usePathname } from "next/navigation";
import React, { useEffect } from "react";
import Link from "next/link";
import countries from "@/lib/countries.json";
import { useCountryListStore } from "@/store/countryListStore";
import { FiSearch } from "react-icons/fi";

export const CountryList = () => {
  const [filter, setFilter] = React.useState("");
  const isOpen = useCountryListStore((state) => state.isOpen);
  const setIsOpen = useCountryListStore((state) => state.setIsOpen);
  const toggleSidebar = useCountryListStore((state) => state.toggle);
  const pathName = usePathname();

  useEffect(() => {
    if (pathName.startsWith("/country/")) {
      setIsOpen(false);
    }
  }, [pathName, setIsOpen]);

  useEffect(() => {
    if (!isOpen) {
      setFilter("");
    }
  }, [isOpen]);

  const handleSearch = (value: string) => {
    setFilter(value);
  };

  const filteredCountries = countries.filter((country) =>
    country.name.toLowerCase().includes(filter.toLowerCase())
  );


  const handleClick = () => {
    if (!isOpen) {
      setIsOpen(true);
    }
  };

  return (
    <div className={`${!isOpen ? "group" : ""}`}>
      <div
        className={`country-list bg-white/80 backdrop-blur-md fixed left-0 z-50 h-[calc(100vh-54px)] overflow-y-scroll transition-all duration-300 ease-in-out ${isOpen ? "w-64" : "w-10 cursor-pointer"} `}
        style={{ overflowY: 'scroll' }}
        onClick={handleClick}
      >
        {/* Content visible only when open */}
        {isOpen && (
          <div className="p-4">
            {/* Search input */}
            <div className="sticky top-0 z-10 bg-white p-4 pl-0">
              <input
                type="search"
                placeholder="Search a country"
                className="border-none w-full px-2 py-1"
                onChange={(e) => handleSearch(e.target.value)}
              />
              <FiSearch className="absolute right-5 top-1/2 -translate-y-1/2 text-black pointer-events-none" />
            </div>

            {/* Country list */}
            <div className="max-h-100">
              <ul className="space-y-2 mt-2 flex flex-col h-full">
                {filteredCountries.map((country) => (
                  <li key={country.code}>
                    <Link
                      href={`/country/${country.code}`}
                      className="block p-1 text-gray-900 hover:bg-gray-900 hover:text-white transition"
                      onClick={() => setIsOpen(false)}
                    >
                      {country.name}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

      </div>
      <button
        onClick={toggleSidebar}
        className="toggle-country-list bg-transparent transition-all duration-300 ease-in-out"
        style={{
          position: 'absolute',
          top: '50%',
          left: isOpen ? "264px" : "12px",
          transform: 'translateY(-50%)',
          zIndex: 100,
          pointerEvents: 'auto',
        }}
      >
        <svg
          width="18"
          height="31"
          viewBox="0 0 18 31"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          className={`transition-transform duration-300 ${isOpen ? "rotate-180" : ""} ${!isOpen ? "group-hover:scale-125" : ""}`}
        >
          <path d="M2 2L15.5 15.5L2 29" stroke="black" strokeWidth="3" />
        </svg>
      </button>
    </div>
  );
};

// nuxt-project/app/components/CountryList.vue
<template>
  <div class="country-list-drawer">
    <div ref="panelRef" class="country-list-panel" :class="{ open: isCountryListOpen, closed: !isCountryListOpen }"
      @click="handlePanelClick">
      <div v-if="isCountryListOpen" class="country-list-content" @click.stop>
        <div class="country-list-search">
          <label :for="searchInputId" class="sr-only">search</label>
          <div class="country-list-search-field">
            <svg viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
              <circle cx="8" cy="8" r="6" stroke="currentColor" stroke-width="1.5" />
              <line x1="12.5" y1="12.5" x2="17" y2="17" stroke="currentColor" stroke-width="1.5"
                stroke-linecap="round" />
            </svg>
            <input :id="searchInputId" v-model="search" type="search" autocomplete="off" placeholder="search"
              class="country-list-search-input" />
          </div>
        </div>
        <ul class="country-list-items">
          <li v-for="country in filteredCountries" :key="country.code" class="country-list-item">
            <NuxtLink :to="`/country/${country.code.toLowerCase()}`" class="country-link p-4" @click="closeCountryList">
              <span class="country-continent">{{ country.continent }}</span>
              <div class="flex w-full">
                <span class="country-name pl-3">{{ country.name }}</span>
                <img :src="`https://flagsapi.com/${country.code}/flat/64.png`" style="height: 24px;"
                  class="country-flag" />
              </div>
            </NuxtLink>
          </li>
          <li v-if="filteredCountries.length === 0" class="country-list-empty">
            Aucun pays ne correspond à votre recherche.
          </li>
        </ul>
      </div>
    </div>
    <button ref="toggleButtonRef" type="button" class="country-list-toggle" :class="{ open: isCountryListOpen }"
      @click.stop="toggleCountryList" aria-label="Basculer la liste des pays" :aria-expanded="isCountryListOpen">
      <img :src="toggleIcon" alt="" class="country-list-toggle-icon white-icon" />
    </button>
  </div>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import toggleIcon from '../assets/icons/toggle.svg?url'
import { countries, type CountryEntry } from '~/data/countries'
import { useCountryListStore } from '~/stores/countryList'

const searchInputId = 'country-search'
const countryListStore = useCountryListStore()
const isCountryListOpen = computed(() => countryListStore.isCountryListOpen)
const search = ref('')
const panelRef = ref<HTMLElement | null>(null)
const toggleButtonRef = ref<HTMLElement | null>(null)

const filteredCountries = computed<CountryEntry[]>(() => {
  const term = search.value.trim().toLowerCase()
  if (!term) {
    return countries
  }
  return countries.filter((country) => country.name.toLowerCase().includes(term))
})

watch(isCountryListOpen, (open) => {
  if (!open) {
    search.value = ''
  }
})

const handleDocumentPointerDown = (event: PointerEvent) => {
  if (!isCountryListOpen.value) return
  if (!(event.target instanceof Node)) return
  if (panelRef.value?.contains(event.target)) return
  if (toggleButtonRef.value?.contains(event.target)) return
  closeCountryList()
}

onMounted(() => {
  document.addEventListener('pointerdown', handleDocumentPointerDown)
})

onBeforeUnmount(() => {
  document.removeEventListener('pointerdown', handleDocumentPointerDown)
})

const toggleCountryList = () => countryListStore.toggle()
const closeCountryList = () => countryListStore.setIsCountryListOpen(false)
const handlePanelClick = () => {
  if (!isCountryListOpen.value) {
    toggleCountryList()
  }
}
</script>
<style scoped>
.country-list-drawer {
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  z-index: 45;
  display: flex;
  align-items: stretch;
  pointer-events: none;
  --drawer-open-width: 280px;
  --drawer-closed-width: 0px;
}

.country-list-panel {
  pointer-events: all;
  width: var(--drawer-open-width);
  max-height: 100vh;
  background: rgba(7, 11, 18, 0.98);
  backdrop-filter: blur(18px);
  box-shadow: 6px 0 30px rgba(0, 0, 0, 0.45);
  transition: width 260ms ease, box-shadow 260ms ease;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.country-list-panel.closed {
  width: var(--drawer-closed-width);
}

.country-list-content {
  display: flex;
  flex-direction: column;
  height: 100%;
  background-color: white;
}

.country-list-search {
  padding: 1.25rem 1.5rem 0.75rem;
}

.country-list-search-field {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.05);
  padding: 0.35rem 0rem;
  color: #656262;
}

.country-list-search-field svg {
  width: 18px;
  height: 18px;
  stroke: currentColor;
  opacity: 0.7;
}

.country-list-search-input {
  flex: 1;
  border: none;
  background: transparent;
  color: inherit;
  outline: none;
  font-size: 0.95rem;
}

.country-list-items {
  margin: 0;
  list-style: none;
  padding: 0 0 1.5rem 0;
  flex: 1;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
}

.country-list-item {
  /* padding: 0 1.5rem; */
  width: 100%;
}

.country-link:hover {
  background-color: black !important;
  color: white;
}

.country-link {
  display: flex;
  justify-content: space-between;
  align-items: center;
  text-decoration: none;
  color: inherit;
  padding: 0.35rem 1.75rem;
  transition: background 200ms ease;
}

.country-link:hover {
  background: rgba(255, 255, 255, 0.08);
}

.country-link:hover {
  .country-continent {
    opacity: 0.8;
    color: white;

  }
}

.country-name {
  font-size: 0.95rem;
  font-weight: 500;
}

.country-continent {
  font-size: 0.75rem;
  color: black;
  opacity: 0.6;
}

.country-list-empty {
  margin: 0 1.5rem;
  font-size: 0.85rem;
  color: rgba(255, 255, 255, 0.6);
}

.country-list-toggle {
  pointer-events: all;
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  /* left: calc(var(--drawer-closed-width) - 2px); */
  background: black;
  border: none;
  width: 58px;
  height: 111px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: left 260ms ease, background 220ms ease;
}

.country-list-toggle-icon.white-icon {
  filter: brightness(0) invert(1);
  /* ou plus court : */
  /* filter: invert(1); */
}

.country-list-toggle.open {
  left: calc(var(--drawer-open-width));
}

.country-list-toggle-icon {
  width: 18px;
  height: 32px;
  object-fit: contain;
  filter: invert(1) sepia(0) saturate(50) brightness(1.5);
  transition: transform 220ms ease;
}

.country-list-toggle.open .country-list-toggle-icon {
  transform: rotate(180deg);
}

.country-flag {
  position: relative;
  margin-left: 0.px;
  position: relative;
  margin-left: auto;
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}
</style>
